import Head from "next/head";
import { useState, useRef, useEffect } from "react";

export default function Home() {
  const [chapter, setChapter] = useState();
  const [imagesUrl, setImagesUrl] = useState([]);
  const chapterRef = useRef(null);

  const handleClick = (e) => {
    e.preventDefault();
    setChapter(chapterRef.current.value);
  };

  useEffect(() => {
    setChapter(localStorage.getItem("lastChapter"));
  }, []);

  useEffect(() => {
    localStorage.setItem("lastChapter", chapterRef.current.value);
    getChapter();
  }, [chapter]);

  const getChapter = () => {
    let urls = [];
    for (let i = 1; i <= 25; i++) {
      urls.push(
        `https://cdn.berserkchapters.com/file/mangap/1/200${
          chapter < 10 ? "0" + chapter : chapter
        }000/${i}.jpg`
      );
    }
    setImagesUrl(urls);
  };

  const handleNextChapter = (e) => {
    setChapter(parseInt(chapter) + 1);
    scroll(0, 0);
  };

  return (
    <div>
      <Head>
        <title>Berserk Manga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="apple-touch-icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen lg:w-2/4 mx-auto flex flex-col items-center gap-1 py-4">
        <form className="flex gap-2 justify-center">
          <label>Kapitel</label>
          <input className="w-24" type="number" ref={chapterRef} />
          <button
            className="rounded-md bg-rose-800 px-4 text-white"
            onClick={handleClick}
          >
            Get Manga
          </button>
        </form>
        {chapter && <h1 className="text-3xl my-2">Kapitel {chapter}</h1>}
        {imagesUrl.map((url, index) => (
          <img
            key={index}
            src={url}
            alt=""
            onerror="this.style.display='none'"
          />
        ))}
        {chapter && (
          <button
            className="rounded-md bg-rose-800 px-4 py-1 w-48 -mt-2 text-white"
            onClick={handleNextChapter}
          >
            Next
          </button>
        )}
      </main>
    </div>
  );
}
